# Site settings
title: matevarga / monadic.consulting
email: mate@mndc.co
description: > # this means to ignore newlines until "baseurl:"
  Notes of Mate Varga @ monadic consulting
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mndc.github.io" # the base hostname & protocol for your site
github_username:  matevarga

# Build settings
markdown: kramdown
